In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("JobsA.csv", encoding="latin1")

In [3]:
df

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
0,85008768,NaN,Licensed Insurance Agent,While many industries were hurt by the last fe...,52000.0,NaN,45760.0,YEARLY,Full-time,"Chico, CA",...,1710000000000,NaN,NaN,NaN,1690000000000,NaN,1,FULL_TIME,USD,BASE_SALARY
1,133114754,77766802.0,Sales Manager,Are you a dynamic and creative marketing profe...,NaN,NaN,NaN,NaN,Full-time,"Santa Clarita, CA",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,FULL_TIME,NaN,NaN
2,133196985,1089558.0,Model Risk Auditor,Join Us as a Model Risk Auditor â Showcase Y...,NaN,NaN,NaN,NaN,Contract,"New York, NY",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,CONTRACT,NaN,NaN
3,381055942,96654609.0,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,NaN,NaN,NaN,NaN,Full-time,"Forney, TX",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,FULL_TIME,NaN,NaN
4,529257371,1244539.0,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,NaN,NaN,NaN,NaN,Full-time,"New York, NY",...,1710000000000,NaN,NaN,NaN,1690000000000,NaN,1,FULL_TIME,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5462,3693592087,1103.0,Business Transformation Manager,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Alpharetta, GA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,NaN,NaN
5463,3693592089,1103.0,Retail Sales Associate,When you join Verizon\n\nVerizon is one of the...,56000.0,NaN,43000.0,YEARLY,Full-time,"Portage, MI",...,1700000000000,NaN,Entry level,NaN,1690000000000,www.aplitrak.com,1,FULL_TIME,USD,BASE_SALARY
5464,3693592090,1103.0,Technical Architect - Telecom,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Ashburn, VA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,NaN,NaN
5465,3693592095,1103.0,Business Sales Account Manager,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Boston, MA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,1,FULL_TIME,NaN,NaN
5466,3693592096,1103.0,Channel Management Consultant,When you join Verizon\n\nVerizon is one of the...,181000.0,NaN,89000.0,YEARLY,Full-time,"Basking Ridge, NJ",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,USD,BASE_SALARY

LOAD DATA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5467 entries, 0 to 5466
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      5467 non-null   int64
 1   company_id                  5316 non-null   float64
 2   title                       5467 non-null   object
 3   description                 5467 non-null   object
 4   max_salary                  2087 non-null   float64
 5   med_salary                  260 non-null    float64
 6   min_salary                  2087 non-null   float64
 7   pay_period                  2347 non-null   object
 8   formatted_work_type         5467 non-null   object
 9   location                    5467 non-null   object
 10  applies                     3656 non-null   float64
 11  original_listed_time        5467 non-null   int64
 12  remote_allowed              912 non-null    float64
 13  views                       5065 non-null   float64
 14  job_posting_url             5467 non-null   object
 15  application_url             2323 non-null   object
 16  application_type            5467 non-null   object
 17  expiry                      5467 non-null   int64
 18  closed_time                 512 non-null    float64
 19  formatted_experience_level  3328 non-null   object
 20  skills_desc                 32 non-null     object
 21  listed_time                 5467 non-null   int64
 22  posting_domain              1890 non-null   object
 23  sponsored                   5467 non-null   int64
 24  work_type                   5467 non-null   object
 25  currency                    2347 non-null   object
 26  compensation_type           2347 non-null   object
dtypes: float64(8), int64(5), object(14)
memory usage: 1.1+ MB

In [5]:
df.describe()

,job_id,company_id,max_salary,med_salary,min_salary,applies,original_listed_time,remote_allowed,views,expiry,closed_time,listed_time,sponsored
count,5.467000e+03,5.316000e+03,2087.000000,260.000000,2087.000000,3656.000000,5.467000e+03,912.0,5065.000000,5.467000e+03,5.120000e+02,5.467000e+03,5467.000000
mean,3.678983e+09,1.188052e+07,76818.505841,28732.402846,55888.047360,28.654814,1.690000e+12,1.0,99.095558,1.701033e+12,1.690000e+12,1.690000e+12,0.317359
std,1.668231e+08,2.396678e+07,85117.849583,53427.402623,55229.288825,68.173221,0.000000e+00,0.0,200.028264,3.173852e+09,0.000000e+00,0.000000e+00,0.465491
min,8.500877e+07,1.016000e+03,10.000000,10.000000,10.000000,1.000000,1.690000e+12,1.0,1.000000,1.690000e+12,1.690000e+12,1.690000e+12,0.000000
25%,3.693048e+09,1.887800e+04,46.865000,18.500000,37.705000,3.000000,1.690000e+12,1.0,13.000000,1.700000e+12,1.690000e+12,1.690000e+12,0.000000
50%,3.693055e+09,6.288270e+05,68000.000000,37.590000,55000.000000,9.000000,1.690000e+12,1.0,43.000000,1.700000e+12,1.690000e+12,1.690000e+12,0.000000
75%,3.693072e+09,1.023214e+07,120000.000000,45760.000000,90000.000000,27.000000,1.690000e+12,1.0,105.000000,1.700000e+12,1.690000e+12,1.690000e+12,1.000000
max,3.693592e+09,9.856222e+07,800000.000000,270890.090000,600000.000000,1615.000000,1.690000e+12,1.0,5656.000000,1.710000e+12,1.690000e+12,1.690000e+12,1.000000

In [6]:
df.head()

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
0,85008768,NaN,Licensed Insurance Agent,While many industries were hurt by the last fe...,52000.0,NaN,45760.0,YEARLY,Full-time,"Chico, CA",...,1710000000000,NaN,NaN,NaN,1690000000000,NaN,1,FULL_TIME,USD,BASE_SALARY
1,133114754,77766802.0,Sales Manager,Are you a dynamic and creative marketing profe...,NaN,NaN,NaN,NaN,Full-time,"Santa Clarita, CA",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,FULL_TIME,NaN,NaN
2,133196985,1089558.0,Model Risk Auditor,Join Us as a Model Risk Auditor â Showcase Y...,NaN,NaN,NaN,NaN,Contract,"New York, NY",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,CONTRACT,NaN,NaN
3,381055942,96654609.0,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,NaN,NaN,NaN,NaN,Full-time,"Forney, TX",...,1700000000000,NaN,NaN,NaN,1690000000000,NaN,0,FULL_TIME,NaN,NaN
4,529257371,1244539.0,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,NaN,NaN,NaN,NaN,Full-time,"New York, NY",...,1710000000000,NaN,NaN,NaN,1690000000000,NaN,1,FULL_TIME,NaN,NaN

In [7]:
df.tail()

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
5462,3693592087,1103.0,Business Transformation Manager,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Alpharetta, GA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,NaN,NaN
5463,3693592089,1103.0,Retail Sales Associate,When you join Verizon\n\nVerizon is one of the...,56000.0,NaN,43000.0,YEARLY,Full-time,"Portage, MI",...,1700000000000,NaN,Entry level,NaN,1690000000000,www.aplitrak.com,1,FULL_TIME,USD,BASE_SALARY
5464,3693592090,1103.0,Technical Architect - Telecom,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Ashburn, VA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,NaN,NaN
5465,3693592095,1103.0,Business Sales Account Manager,When you join Verizon\n\nVerizon is one of the...,NaN,NaN,NaN,NaN,Full-time,"Boston, MA",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,1,FULL_TIME,NaN,NaN
5466,3693592096,1103.0,Channel Management Consultant,When you join Verizon\n\nVerizon is one of the...,181000.0,NaN,89000.0,YEARLY,Full-time,"Basking Ridge, NJ",...,1700000000000,NaN,Mid-Senior level,NaN,1690000000000,www.aplitrak.com,0,FULL_TIME,USD,BASE_SALARY

DATA CLEANING

In [8]:
df = df.drop(['Unnamed: 27','med_salary', 'max_salary', 'min_salary', 'formatted_work_type','expiry','listed_time','formatted_experience_level','original_listed_time','views',
              'skills_desc', 'company_id', 'closed_time','job_posting_url','sponsored', 'posting_domain', 'currency',
              'compensation_type', 'application_type', 'application_url'], axis=1, errors='ignore')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5467 entries, 0 to 5466
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          5467 non-null   int64
 1   title           5467 non-null   object
 2   description     5467 non-null   object
 3   pay_period      2347 non-null   object
 4   location        5467 non-null   object
 5   applies         3656 non-null   float64
 6   remote_allowed  912 non-null    float64
 7   work_type       5467 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 341.8+ KB

In [10]:
df.isnull().sum()

job_id               0
title                0
description          0
pay_period        3120
location             0
applies           1811
remote_allowed    4555
work_type            0
dtype: int64

In [11]:
df['pay_period'].fillna(df['pay_period'].mode()[0], inplace=True)

In [12]:
df.isnull().sum()

job_id               0
title                0
description          0
pay_period           0
location             0
applies           1811
remote_allowed    4555
work_type            0
dtype: int64

In [13]:
df['applies']=df['applies'].fillna(0)

In [14]:
df.isnull().sum()

job_id               0
title                0
description          0
pay_period           0
location             0
applies              0
remote_allowed    4555
work_type            0
dtype: int64

In [15]:
df['remote_allowed']=df['remote_allowed'].fillna(0)

In [16]:
df.isnull().sum()

job_id            0
title             0
description       0
pay_period        0
location          0
applies           0
remote_allowed    0
work_type         0
dtype: int64

In [17]:
df['description'].fillna(df['description'].mode()[0], inplace=True)

In [18]:
df.isnull().sum()

job_id            0
title             0
description       0
pay_period        0
location          0
applies           0
remote_allowed    0
work_type         0
dtype: int64

In [19]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import NearestNeighbors
import pickle

def preprocess_text(df):
    """Preprocesses job descriptions by merging text fields and converting to lowercase."""
    df = df.copy()
    df[['title', 'description', 'skills_desc']] = df[['title', 'description', 'skills_desc']].astype(str)
    df['text'] = (df['title'] + ' ' + df['description'] + ' ' + df['skills_desc']).str.lower()
    return df

def build_bert_knn_model(df):
    """Builds a BERT-based embedding model and KNN model."""
    model = SentenceTransformer('all-MiniLM-L6-v2')
    job_embeddings = model.encode(df['text'].tolist(), convert_to_numpy=True)
    knn = NearestNeighbors(n_neighbors=10, metric='cosine', algorithm='brute', n_jobs=-1).fit(job_embeddings)
    
    # Save the model, KNN, and embeddings
    with open("job_model.pkl", "wb") as f:
        pickle.dump((model, knn, job_embeddings, df), f)

    print("\n\033[1;32mModel trained and saved successfully!\033[0m")

if __name__ == "__main__":
    try:
        file_path = r"C:\Users\vishn\Jobs.csv"
        df = pd.read_csv(file_path)
        df = preprocess_text(df)
        build_bert_knn_model(df)
    except Exception as e:
        print("\n\033[1;31mError:\033[0m", str(e))

Model trained and saved successfully!

In [ ]:
import numpy as np
import pickle
import nltk
from nltk.corpus import wordnet

def expand_skills(skills):
    """Expands skills by finding synonyms using WordNet."""
    expanded_skills = set(skills.split())
    for word in skills.split():
        for syn in wordnet.synsets(word):
            for lemma in syn.lemmas():
                expanded_skills.add(lemma.name().replace('_', ' '))
    return ' '.join(expanded_skills)

def get_recommendations(job_input, model, knn, job_embeddings, df, num_recommendations=5, similarity_threshold=0.35):
    """Retrieves job recommendations based on BERT embeddings and cosine similarity."""
    if df.empty:
        return None, None, None
    
    expanded_input = expand_skills(job_input.lower())
    input_embedding = model.encode([expanded_input], convert_to_numpy=True)
    distances, indices = knn.kneighbors(input_embedding)
    
    recommendations = []
    similarity_scores = 1 - distances[0]  # Convert distances to similarity scores
    
    filtered_scores = [
        round(similarity_scores[i], 4)
        for i in range(len(indices[0])) if similarity_scores[i] > similarity_threshold
    ]
    
    for i, score in zip(indices[0], filtered_scores):
        job = df.iloc[i]
        recommendations.append({
            "title": job.get('title', 'N/A'),
            "company": job.get('company_id', 'N/A'),
            "location": job.get('location', 'N/A'),
            "description": job.get('description', 'N/A')[:500] + "...",
            "work_type": job.get('formatted_work_type', 'N/A'),
            "similarity_score": score
        })
    
    mean_similarity = round(np.mean(filtered_scores), 4) if filtered_scores else 0
    median_similarity = round(np.median(filtered_scores), 4) if filtered_scores else 0
    
    return recommendations[:num_recommendations], mean_similarity, median_similarity

if __name__ == "__main__":
    try:
        # Load trained model
        with open("job_model.pkl", "rb") as f:
            model, knn, job_embeddings, df = pickle.load(f)
        
        user_input = input("\nEnter your skills: ")
        recommendations, mean_similarity, median_similarity = get_recommendations(user_input, model, knn, job_embeddings, df)
        
        if recommendations:
            print("\n\033[1mTop Matching Jobs (Similarity > 35%):\033[0m")
            for idx, job in enumerate(recommendations, start=1):
                print(f"\n\033[1;34mJob {idx}:\033[0m")
                print("\033[1mTitle:\033[0m", job['title'])
                print("\033[1mCompany ID:\033[0m", job['company'])
                print("\033[1mLocation:\033[0m", job['location'])
                print("\033[1mWork Type:\033[0m", job['work_type'])
                print("\033[1mSimilarity Score:\033[0m", job['similarity_score'])
                print("\033[1mDescription:\033[0m", job['description'])
            
            print(f"\n\033[1;32mMean Similarity Score:\033[0m {mean_similarity}")
            print(f"\n\033[1;33mMedian Similarity Score:\033[0m {median_similarity}")
        else:
            print("\n\033[1;31mNo matching jobs found with similarity > 35%.\033[0m")
    except Exception as e:
        print("\n\033[1;31mError:\033[0m", str(e))

In [ ]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Example dataset (replace with your actual embeddings)
job_embeddings = np.random.rand(100, 384)  # Assuming 100 job descriptions and 384-d embeddings

# Train the KNN model
knn = NearestNeighbors(n_neighbors=10, metric='cosine', algorithm='brute', n_jobs=-1)
knn.fit(job_embeddings)

# Now you can save it
import pickle
with open('job_recc_ardra.pkl', 'wb') as file:
    pickle.dump(knn, file)

print("Model saved successfully!")